"""Import every model so ``Base.metadata`` is complete for Alembic and create_all."""
from app.models.admin import (
    AIModel,
    AIProvider,
    AIUsage,
    APIKey,
    Connector,
    CostTracking,
    ScoringRule,
    ServiceCatalogItem,
)
from app.models.agent import (
    Agent,
    AgentExecution,
    AgentLog,
    AgentMessage,
    AgentTask,
    AIMemory,
)
from app.models.base import JSONBType, ProvenanceMixin, TimestampMixin, UUIDMixin, utcnow
from app.models.campaign import Campaign, CampaignFilter, ResearchJob
from app.models.company import (
    Activity,
    AIResearch,
    BuyingSignal,
    Company,
    CompanyLocation,
    CompanySource,
    CompanyVerification,
    Contact,
    DecisionMaker,
    EmailVerification,
    Evidence,
    Export,
    HumanFeedback,
    OpportunityScore,
    PhoneVerification,
    PipelineEntry,
    ResearchFinding,
    Technology,
    Website,
    WebsiteFeature,
    WebsitePage,
)
from app.models.geo import City, Country, Industry, Region
from app.models.org import AuditLog, Organization, Permission, Role, User

__all__ = [
    "Activity",
    "Agent",
    "AgentExecution",
    "AgentLog",
    "AgentMessage",
    "AgentTask",
    "AIMemory",
    "AIModel",
    "AIProvider",
    "AIResearch",
    "AIUsage",
    "APIKey",
    "AuditLog",
    "BuyingSignal",
    "Campaign",
    "CampaignFilter",
    "City",
    "Company",
    "CompanyLocation",
    "CompanySource",
    "CompanyVerification",
    "Connector",
    "Contact",
    "CostTracking",
    "Country",
    "DecisionMaker",
    "EmailVerification",
    "Evidence",
    "Export",
    "HumanFeedback",
    "Industry",
    "JSONBType",
    "OpportunityScore",
    "Organization",
    "Permission",
    "PhoneVerification",
    "PipelineEntry",
    "ProvenanceMixin",
    "Region",
    "ResearchFinding",
    "ResearchJob",
    "Role",
    "ScoringRule",
    "ServiceCatalogItem",
    "Technology",
    "TimestampMixin",
    "User",
    "UUIDMixin",
    "Website",
    "WebsiteFeature",
    "WebsitePage",
    "utcnow",
]
